<?php

/**
 * General settings file.
 *
 */

// Database Settings

$db_user = $config["db_user"]; 						// Database username
$db_pass = $config["db_pwd"];						// Database password
$db_name = $config["db_name"]; 						// Database name
$db_host = "localhost";					// Database host
$db_port = "";						// Database port


// Parser settings

$parser_path = "../../";				// Path to Excel without /

?>